# Generated by Django 4.0.3 on 2022-03-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='旅行日時')),
                ('transportation', models.CharField(max_length=20, verbose_name='交通手段')),
                ('cost', models.IntegerField(default=100)),
                ('member', models.CharField(max_length=30, verbose_name='メンバー')),
                ('thoughts', models.TextField(blank=True, verbose_name='概要')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
        ),
    ]
